#!/bin/sh

set -e

die_install() {
  echo "${0}: Please install $1 ($2)"
  exit 1
}

[ -x "`which devd`" ] || die_install devd https://github.com/cortesi/devd
[ -x "`which watchexec`" ] || die_install watchexec https://github.com/mattgreen/watchexec
[ -x "`which yarn`" ] || die_install yarn https://yarnpkg.com/

yarn install

node_modules/.bin/elm-package install --yes

echo OK
