def lame_builder(options):
  return Builder(action = "env lame %s $SOURCE $TARGET" % ' '.join(options),
                 suffix = '.mp3')

lame_options = ['--ta "Null Artist"',
                '--tl "Null Album"',
                '--tt "Null Title"',
               ]
lamev1_options = lame_options + ['--id3v1-only']
lamev2_options = lame_options + ['--id3v2-only']

env = Environment(BUILDERS = {'Lame': lame_builder([]),
                              'LameV1': lame_builder(lamev1_options),
                              'LameV2': lame_builder(lamev2_options),
                             }
                 )

env.Lame(source = 'null', target = 'null-noid3')
env.LameV1(source = 'null', target = 'null-v1')
env.LameV2(source = 'null', target = 'null-v2')
